### PR TITLE
remove selinux

### PR DESCRIPTION
**Pull request by siscia**

### CODE REVIEW

**Comment by jblomer** [comment]
Wait, this might make trouble on SL7 nodes.  The problem is that the version of selinux on the build machine is a minimum requirement for installation.  That means, older SL7 nodes cannot install what newer SL7 nodes built.

**Comment by siscia** [comment]
Awww I see!

I also upgraded the version of cc7, from cc7.3 to cc7.7 should I revert back that too?

**Comment by jblomer** [comment]
I think the general os upgrade is fine... we'll see :)

**Comment by siscia** [comment]
Fixed back!
https://github.com/cernvm/ci-scripts/commit/4f7255896a326e07a741df92c555a23d7f4474bc

**Pull request merged**
