### PR TITLE
update the go compiler

### PR DESCRIPTION
**Pull request by siscia**
@jblomer, @radupopescu 

thoughts?

### CODE REVIEW

**Comment by radupopescu** [comment]
I don't remember why the Go version from EPEL cannot be used.

**Comment by siscia** [comment]
Because I need go 1.11.5

We are moving the ducc code into the cvmfs repository which is not anymore in any GOPATH/GOROOT, and the standard `go build` workflow will break.

Another solution would be to hack around during compilation the GOPATH variable, and that would work. However I still require go >= 1.10 that I don't see offered from EPEL.

At this point, since I need anyway to use a newer compiler I just upgrade to 1.11.5 that has support for `go mod` and make the compilation GOPATH independent.

**Comment by radupopescu** [comment]
EPEL has Go 1.11.4 is that ok?

**Comment by siscia** [comment]
Yes you are right, closing for #29 

Sorry I tried to install from EPEL on my test machines and it didn't work, mostly a mistake of mine in the setting of the repo.

**Pull request closed without merging**
