### PR TITLE
Trying new images

### PR DESCRIPTION
**Pull request by siscia**

### CODE REVIEW

**Comment by siscia** [comment]
I don't like the huge switch, but it is either there or in the filesystem. And I prefered to make it explicit.

I am finalizing some problem with SLC6, that was not simple to build. But we should be there.

**Comment by jblomer** [comment]
Excellent!  Please feel free to merge once ready.

**Comment by siscia** [comment]
I also removed all the code related to the old way of using docker images.

I believe it is not needed anymore.

Should we remove also the docker images from this repo? I feel safer having them around, but on the other hand we can always get them back from history and they can confuse people.

**Comment by jblomer** [comment]
Let them in just for a little bit and clean-up next time we stumble across them.  We can add a README in the directory along these lines ("deprecated, remove me soon...").

**Pull request merged**
